/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Statistics;

/**
 *
 * @author norha
 */
public class jLeaderBoard extends javax.swing.JPanel {

    /**
     * Creates new form jLeaderBoard
     */
    public jLeaderBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMostSoldItem = new javax.swing.JLabel();
        jMostSoldCategory = new javax.swing.JLabel();
        jUserWithTheMostSales = new javax.swing.JLabel();
        jUserWithTheMostDeals = new javax.swing.JLabel();
        jUserWithTheMostImports = new javax.swing.JLabel();
        jMostSoldItemScore = new javax.swing.JLabel();
        jMostSoldCategoryScore = new javax.swing.JLabel();
        jUserWithTheMostSalesScore = new javax.swing.JLabel();
        jUserWithTheMostDealsScore = new javax.swing.JLabel();
        jUserWithTheMostImportsScore = new javax.swing.JLabel();
        jBack2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPeriod = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 56)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Statistics/Icons/winner.png"))); // NOI18N
        jLabel2.setText("  LEADERBOARD");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Most Sold Item");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Most Sold Category");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("User With The Most Sales");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("User With The Most Deals");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("User With The Most Imports");

        jMostSoldItem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMostSoldItem.setText("jLabel3");

        jMostSoldCategory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMostSoldCategory.setText("jLabel4");

        jUserWithTheMostSales.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostSales.setText("jLabel5");

        jUserWithTheMostDeals.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostDeals.setText("jLabel6");

        jUserWithTheMostImports.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostImports.setText("jLabel7");

        jMostSoldItemScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMostSoldItemScore.setText("jLabel3");

        jMostSoldCategoryScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMostSoldCategoryScore.setText("jLabel4");

        jUserWithTheMostSalesScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostSalesScore.setText("jLabel5");

        jUserWithTheMostDealsScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostDealsScore.setText("jLabel6");

        jUserWithTheMostImportsScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jUserWithTheMostImportsScore.setText("jLabel7");

        jBack2.setBackground(new java.awt.Color(217, 156, 69));
        jBack2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jBack2.setForeground(new java.awt.Color(255, 255, 255));
        jBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/Roles/back.png"))); // NOI18N
        jBack2.setMnemonic('b');
        jBack2.setText("    Back   ");
        jBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack2MouseClicked(evt);
            }
        });
        jBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBack2ActionPerformed(evt);
            }
        });

        jGroup.add(jRadioButton1);
        jRadioButton1.setText("Today");

        jGroup.add(jRadioButton2);
        jRadioButton2.setText("This Week");

        jGroup.add(jRadioButton3);
        jRadioButton3.setText("This Month");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jGroup.add(jRadioButton4);
        jRadioButton4.setText("This Year");

        jPeriod.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jPeriod.setText("Period");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMostSoldCategory)
                                    .addComponent(jUserWithTheMostSales)
                                    .addComponent(jUserWithTheMostDeals)
                                    .addComponent(jMostSoldItem)
                                    .addComponent(jUserWithTheMostImports))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUserWithTheMostImportsScore)
                                    .addComponent(jMostSoldCategoryScore)
                                    .addComponent(jMostSoldItemScore)
                                    .addComponent(jUserWithTheMostSalesScore)
                                    .addComponent(jUserWithTheMostDealsScore))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPeriod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUserWithTheMostDealsScore)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jMostSoldItemScore))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jMostSoldCategoryScore))
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jUserWithTheMostSalesScore))
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jUserWithTheMostImportsScore)
                            .addComponent(jUserWithTheMostImports)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMostSoldItem)
                                .addGap(39, 39, 39)
                                .addComponent(jMostSoldCategory)
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUserWithTheMostSales)
                                .addGap(44, 44, 44)
                                .addComponent(jUserWithTheMostDeals)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack2MouseClicked
        

    }//GEN-LAST:event_jBack2MouseClicked

    private void jBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBack2ActionPerformed
        
    }//GEN-LAST:event_jBack2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JButton jBack1;
    private javax.swing.JButton jBack2;
    private javax.swing.ButtonGroup jGroup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jMostSoldCategory;
    private javax.swing.JLabel jMostSoldCategoryScore;
    private javax.swing.JLabel jMostSoldItem;
    private javax.swing.JLabel jMostSoldItemScore;
    private javax.swing.JLabel jPeriod;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel jUserWithTheMostDeals;
    private javax.swing.JLabel jUserWithTheMostDealsScore;
    private javax.swing.JLabel jUserWithTheMostImports;
    private javax.swing.JLabel jUserWithTheMostImportsScore;
    private javax.swing.JLabel jUserWithTheMostSales;
    private javax.swing.JLabel jUserWithTheMostSalesScore;
    // End of variables declaration//GEN-END:variables
}
